import { z } from "zod";
export declare const SettingsValidation: {
    createSettingsValidationSchema: z.ZodObject<{
        body: z.ZodObject<{
            siteTitle: z.ZodString;
            siteDescription: z.ZodString;
            email: z.ZodEmail;
            phone: z.ZodString;
            address: z.ZodString;
            logo: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            favicon: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            socialLinks: z.ZodDefault<z.ZodObject<{
                github: z.ZodOptional<z.ZodURL>;
                linkedin: z.ZodOptional<z.ZodURL>;
                twitter: z.ZodOptional<z.ZodURL>;
                facebook: z.ZodOptional<z.ZodURL>;
                instagram: z.ZodOptional<z.ZodURL>;
                youtube: z.ZodOptional<z.ZodURL>;
                leetcode: z.ZodOptional<z.ZodURL>;
                hackerrank: z.ZodOptional<z.ZodURL>;
                stackoverflow: z.ZodOptional<z.ZodURL>;
            }, z.core.$strip>>;
            seo: z.ZodObject<{
                metaTitle: z.ZodString;
                metaDescription: z.ZodString;
                metaKeywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
                siteUrl: z.ZodURL;
            }, z.core.$strip>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateSettingsValidationSchema: z.ZodObject<{
        body: z.ZodObject<{
            siteTitle: z.ZodOptional<z.ZodString>;
            siteDescription: z.ZodOptional<z.ZodString>;
            email: z.ZodOptional<z.ZodEmail>;
            phone: z.ZodOptional<z.ZodString>;
            address: z.ZodOptional<z.ZodString>;
            logo: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            favicon: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            socialLinks: z.ZodOptional<z.ZodObject<{
                github: z.ZodOptional<z.ZodURL>;
                linkedin: z.ZodOptional<z.ZodURL>;
                twitter: z.ZodOptional<z.ZodURL>;
                facebook: z.ZodOptional<z.ZodURL>;
                instagram: z.ZodOptional<z.ZodURL>;
                youtube: z.ZodOptional<z.ZodURL>;
                leetcode: z.ZodOptional<z.ZodURL>;
                hackerrank: z.ZodOptional<z.ZodURL>;
                stackoverflow: z.ZodOptional<z.ZodURL>;
            }, z.core.$strip>>;
            seo: z.ZodOptional<z.ZodObject<{
                metaTitle: z.ZodOptional<z.ZodString>;
                metaDescription: z.ZodOptional<z.ZodString>;
                metaKeywords: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString>>>;
                siteUrl: z.ZodOptional<z.ZodURL>;
            }, z.core.$strip>>;
        }, z.core.$strip>;
    }, z.core.$strip>;
};
//# sourceMappingURL=settings.validation.d.ts.map