// src/middlewares/request-logger.middleware.ts

import type { Request, Response } from 'express';
import { pinoHttp } from 'pino-http';

import { logger } from '../shared/logger/index.js';

/**
 * HTTP request logger.
 *
 * Features:
 * - Reuses request ID from requestIdMiddleware
 * - Logs request/response lifecycle
 * - Measures response time
 * - Serializes request/response objects
 * - Automatically logs unhandled errors
 * - Compatible with Pino v10 + pino-http v11
 */
export const requestLoggerMiddleware = pinoHttp({
  /**
   * Base application logger.
   */
  logger,

  /**
   * Reuse request ID generated by requestIdMiddleware.
   */
  genReqId(request) {
    return request.id;
  },

  /**
   * Attribute names in log output.
   */
  customAttributeKeys: {
    req: 'request',
    res: 'response',
    err: 'error',
    responseTime: 'responseTime',
    reqId: 'requestId',
  },

  /**
   * Additional log properties.
   */
  customProps(request) {
    return {
      requestId: request.id,
    };
  },

  /**
   * Successful request message.
   */
  customSuccessMessage(request: Request, response: Response): string {
    return `${request.method} ${request.originalUrl} completed with ${response.statusCode}`;
  },

  /**
   * Error request message.
   */
  customErrorMessage(request: Request, response: Response, error: Error): string {
    return `${request.method} ${request.originalUrl} failed with ${response.statusCode}: ${error.message}`;
  },

  /**
   * Log level selection.
   */
  customLogLevel(_request: Request, response: Response, error?: Error) {
    if (error || response.statusCode >= 500) {
      return 'error';
    }

    if (response.statusCode >= 400) {
      return 'warn';
    }

    return 'info';
  },

  /**
   * Ignore noisy endpoints.
   */
  autoLogging: {
    ignore(request) {
      return (
        request.originalUrl === '/health' ||
        request.originalUrl === '/live' ||
        request.originalUrl === '/ready'
      );
    },
  },

  /**
   * Log received requests.
   */
  quietReqLogger: false,

  /**
   * Log completed responses.
   */
  quietResLogger: false,

  /**
   * Log received request message.
   */
  customReceivedMessage(request: Request): string {
    return `${request.method} ${request.originalUrl} received`;
  },
});

export default requestLoggerMiddleware;
