import { z } from "zod";
export declare const AboutValidation: {
    createAboutValidationSchema: z.ZodObject<{
        body: z.ZodObject<{
            profileImage: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            fullName: z.ZodString;
            designation: z.ZodString;
            bio: z.ZodString;
            email: z.ZodOptional<z.ZodEmail>;
            phone: z.ZodOptional<z.ZodString>;
            address: z.ZodOptional<z.ZodString>;
            resumeUrl: z.ZodOptional<z.ZodURL>;
            yearsOfExperience: z.ZodOptional<z.ZodNumber>;
            stats: z.ZodOptional<z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                value: z.ZodString;
            }, z.core.$strip>>>;
            isActive: z.ZodDefault<z.ZodBoolean>;
        }, z.core.$strip>;
    }, z.core.$strip>;
    updateAboutValidationSchema: z.ZodObject<{
        body: z.ZodObject<{
            profileImage: z.ZodOptional<z.ZodObject<{
                url: z.ZodURL;
                publicId: z.ZodString;
            }, z.core.$strip>>;
            fullName: z.ZodOptional<z.ZodString>;
            designation: z.ZodOptional<z.ZodString>;
            bio: z.ZodOptional<z.ZodString>;
            email: z.ZodOptional<z.ZodEmail>;
            phone: z.ZodOptional<z.ZodString>;
            address: z.ZodOptional<z.ZodString>;
            resumeUrl: z.ZodOptional<z.ZodURL>;
            yearsOfExperience: z.ZodOptional<z.ZodNumber>;
            stats: z.ZodOptional<z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                value: z.ZodString;
            }, z.core.$strip>>>;
            isActive: z.ZodOptional<z.ZodBoolean>;
        }, z.core.$strip>;
    }, z.core.$strip>;
};
//# sourceMappingURL=about.validation.d.ts.map